
parameters:
  name: ''
  displayName: ''
  buildConfiguration: 'Release'
  vmImage: 'ubuntu-16.04'
  imageName: ''

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  container:
    image: ${{ parameters.imageName }}
  steps:

  # Install pipeline dependencies
  - powershell: ./.azure-pipelines/pipeline-deps.ps1
    displayName: 'Install dependencies'

  # Download module
  - task: DownloadPipelineArtifact@2
    displayName: 'Download module'
    inputs:
      artifact: PSRule.Rules.Azure
      path: $(Build.SourcesDirectory)/out/modules/PSRule.Rules.Azure

  # Build module
  - powershell: Invoke-Build TestModule -Configuration ${{ parameters.buildConfiguration }} -Build $(Build.BuildNumber)
    displayName: 'Test module'

  # Pester test results
  - task: PublishTestResults@2
    displayName: 'Publish Pester results'
    inputs:
      testRunTitle: 'Pester on ${{ parameters.imageName }}'
      testRunner: NUnit
      testResultsFiles: 'reports/pester-unit.xml'
      mergeTestResults: true
      platform: ${{ parameters.name }}
      configuration: ${{ parameters.buildConfiguration }}
      publishRunAttachments: true
    condition: succeededOrFailed()
