//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSRule.Rules.Azure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Diagnostics {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Diagnostics() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSRule.Rules.Azure.Resources.Diagnostics", typeof(Diagnostics).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running bicep from &apos;{0}&apos;..
        /// </summary>
        internal static string DebugRunningBicep {
            get {
                return ResourceManager.GetString("DebugRunningBicep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deployment &apos;{0}&apos; with symbolic name &apos;{1}&apos; failed. {2}.
        /// </summary>
        internal static string FailedDeployment {
            get {
                return ResourceManager.GetString("FailedDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanding policy assignments with {0} threads..
        /// </summary>
        internal static string VerboseExpandingPolicyAssignments {
            get {
                return ResourceManager.GetString("VerboseExpandingPolicyAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanding resource: {0}.
        /// </summary>
        internal static string VerboseExpandingResource {
            get {
                return ResourceManager.GetString("VerboseExpandingResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for files in &apos;{0}&apos;..
        /// </summary>
        internal static string VerboseFindFiles {
            get {
                return ResourceManager.GetString("VerboseFindFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found file &apos;{0}&apos;..
        /// </summary>
        internal static string VerboseFoundFile {
            get {
                return ResourceManager.GetString("VerboseFoundFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting policy assignments by Id: {0}.
        /// </summary>
        internal static string VerboseGetAssignmentById {
            get {
                return ResourceManager.GetString("VerboseGetAssignmentById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added {0} assignments by Id..
        /// </summary>
        internal static string VerboseGetAssignmentByIdResult {
            get {
                return ResourceManager.GetString("VerboseGetAssignmentByIdResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting policy assignments from scope: {0}.
        /// </summary>
        internal static string VerboseGetAssignmentByScope {
            get {
                return ResourceManager.GetString("VerboseGetAssignmentByScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added {0} assignments from scope &apos;{1}&apos;..
        /// </summary>
        internal static string VerboseGetAssignmentByScopeResult {
            get {
                return ResourceManager.GetString("VerboseGetAssignmentByScopeResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting resource: {0}.
        /// </summary>
        internal static string VerboseGetResource {
            get {
                return ResourceManager.GetString("VerboseGetResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting resources from subscription: {0}.
        /// </summary>
        internal static string VerboseGetResources {
            get {
                return ResourceManager.GetString("VerboseGetResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added {0} resources from subscription &apos;{1}&apos;..
        /// </summary>
        internal static string VerboseGetResourcesResult {
            get {
                return ResourceManager.GetString("VerboseGetResourcesResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter file &apos;{0}&apos; does not contain a metadata property..
        /// </summary>
        internal static string VerboseMetadataNotFound {
            get {
                return ResourceManager.GetString("VerboseMetadataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrying &apos;{0}&apos; in {1}, attempt {2}..
        /// </summary>
        internal static string VerboseRetryIn {
            get {
                return ResourceManager.GetString("VerboseRetryIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the specified template file &apos;{0}&apos;..
        /// </summary>
        internal static string VerboseTemplateFileNotFound {
            get {
                return ResourceManager.GetString("VerboseTemplateFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter file &apos;{0}&apos; does not reference a linked template..
        /// </summary>
        internal static string VerboseTemplateLinkNotFound {
            get {
                return ResourceManager.GetString("VerboseTemplateLinkNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using TenantId: {0}.
        /// </summary>
        internal static string VerboseUsingTenantId {
            get {
                return ResourceManager.GetString("VerboseUsingTenantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get &apos;{0}&apos;: status={1}, correlation-id={2}, {3}.
        /// </summary>
        internal static string WarnFailedToGet {
            get {
                return ResourceManager.GetString("WarnFailedToGet", resourceCulture);
            }
        }
    }
}
