name: Rule request
description: Suggest the creation of a new or to update an existing rule
title: '[RULE] <title>'
type: Feature
labels: ['rule', 'Needs: Triage :mag:']
body:
  - type: input
    id: name
    attributes:
      label: Existing rule
      description: If this relates to an existing rule include the name of the rule.
      placeholder: Azure.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Suggested rule
      description: A clear and concise description of the what the rule should check and why.
    validations:
      required: true
  - type: dropdown
    id: pillar
    attributes:
      label: Pillar
      description: Which Well-Architected Framework pillar best aligns to this rule?
      multiple: false
      options:
        - Cost Optimization
        - Operational Excellence
        - Performance Efficiency
        - Reliability
        - Security
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Any additional context relating to the rule including links to documentation.

        We recommend including at least one link to Azure Well-Architected Framework or product documentation.
    validations:
      required: false
