# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#
# Rules for Azure Kubernetes Service (AKS)
#

#region Rules

---
# Synopsis: AKS clusters should have minimum number of nodes for failover and updates
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AKS.MinNodeCount
  tags:
    release: 'GA'
    ruleSet: '2020_06'
spec:
  type:
  - Microsoft.ContainerService/managedClusters
  condition:
    field: 'Properties.agentPoolProfiles[0].count'
    greaterOrEquals: 3

---
# Synopsis: Configure AKS clusters to use managed identities for managing cluster infrastructure.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AKS.ManagedIdentity
  tags:
    release: 'GA'
    ruleSet: '2020_06'
spec:
  type:
  - Microsoft.ContainerService/managedClusters
  condition:
    field: 'Identity.Type'
    in:
      - 'SystemAssigned'
      - 'UserAssigned'

---
# Synopsis: Use a Standard load-balancer with AKS clusters.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AKS.StandardLB
  tags:
    release: 'GA'
    ruleSet: '2020_06'
spec:
  type:
  - Microsoft.ContainerService/managedClusters
  condition:
    field: 'Properties.networkProfile.loadBalancerSku'
    equals: 'standard'

---
# Synopsis: Deploy AKS clusters with Network Policies enabled.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AKS.NetworkPolicy
  tags:
    release: 'GA'
    ruleSet: '2020_06'
spec:
  type:
  - Microsoft.ContainerService/managedClusters
  condition:
    field: Properties.networkProfile.networkPolicy
    in:
    - azure
    - calico

---
# Synopsis: AKS clusters should use Azure Policy add-on.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AKS.AzurePolicyAddOn
  tags:
    release: 'GA'
    ruleSet: '2020_12'
spec:
  type:
  - Microsoft.ContainerService/managedClusters
  condition:
    field: 'Properties.addonProfiles.azurePolicy.enabled'
    equals: true

---
# Synopsis: Use AKS-managed Azure AD to simplify authorization and improve security.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AKS.ManagedAAD
  tags:
    release: 'GA'
    ruleSet: '2021_06'
spec:
  type:
  - Microsoft.ContainerService/managedClusters
  condition:
    field: 'Properties.aadProfile.managed'
    equals: true

---
# Synopsis: Restrict access to API server endpoints to authorized IP addresses.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AKS.AuthorizedIPs
  tags:
    release: 'GA'
    ruleSet: '2021_06'
spec:
  type:
  - Microsoft.ContainerService/managedClusters
  condition:
    field: 'Properties.apiServerAccessProfile.authorizedIPRanges'
    greaterOrEquals: 1

---
# Synopsis: Enforce named user accounts with RBAC assigned permissions.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AKS.LocalAccounts
  tags:
    release: 'preview'
    ruleSet: '2021_06'
spec:
  type:
  - Microsoft.ContainerService/managedClusters
  condition:
    field: 'Properties.disableLocalAccounts'
    equals: true

---
# Synopsis: Use Azure RBAC for Kubernetes Authorization with AKS clusters.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AKS.AzureRBAC
  tags:
    release: 'GA'
    ruleSet: '2021_06'
spec:
  type:
  - Microsoft.ContainerService/managedClusters
  condition:
    field: 'Properties.aadProfile.enableAzureRbac'
    equals: true

---
# Synopsis: Deploy AKS clusters with Secrets Store CSI Driver and store Secrets in Key Vayult.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AKS.SecretStore
  tags:
    release: 'GA'
    ruleSet: '2021_12'
spec:
  type:
  - Microsoft.ContainerService/managedClusters
  condition:
    field: Properties.addonProfiles.azureKeyvaultSecretsProvider.enabled
    equals: true

---
# Synopsis: Enable autorotation of Secrets Store CSI Driver secrets for AKS clusters.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AKS.SecretStoreRotation
  tags:
    release: 'GA'
    ruleSet: '2021_12'
spec:
  type:
  - Microsoft.ContainerService/managedClusters
  with:
  - Azure.AKS.SecretStoreEnabled
  condition:
    field: Properties.addonProfiles.azureKeyvaultSecretsProvider.config.enableSecretRotation
    equals: 'true'

---
# Synopsis: Disable HTTP application routing add-on in AKS clusters.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AKS.HttpAppRouting
  tags:
    release: 'GA'
    ruleSet: '2021_12'
spec:
  type:
  - Microsoft.ContainerService/managedClusters
  condition:
    anyOf:
    - field: Properties.addonProfiles.httpApplicationRouting.enabled
      exists: false
    - field: Properties.addonProfiles.httpApplicationRouting.enabled
      equals: false

---
# Synopsis: Configure AKS to automatically upgrade to newer supported AKS versions as they are made available.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AKS.AutoUpgrade
  tags:
    release: 'GA'
    ruleSet: '2021_12'
spec:
  type:
  - Microsoft.ContainerService/managedClusters
  condition:
    allOf:
    - field: Properties.autoUpgradeProfile.upgradeChannel
      hasValue: true
    - field: Properties.autoUpgradeProfile.upgradeChannel
      notEquals: none

---
# Synopsis: Configure AKS clusters to use AAD pod identities to access Azure resources securely.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AKS.PodIdentity
  tags:
    release: 'preview'
    ruleSet: '2021_12'
spec:
  type:
  - Microsoft.ContainerService/managedClusters
  with:
    - Azure.AKS.AzureCNI
  condition:
    field: Properties.podIdentityProfile.enabled
    equals: true

#endregion Rules

#region Selectors

---
# Synopsis: AKS clusters with Secret Store CSI Driver enabled.
apiVersion: github.com/microsoft/PSRule/v1
kind: Selector
metadata:
  name: Azure.AKS.SecretStoreEnabled
spec:
  if:
    allOf:
    - type: '.'
      equals: 'Microsoft.ContainerService/managedClusters'
    - field: Properties.addonProfiles.azureKeyvaultSecretsProvider.enabled
      equals: true

---
# Synopsis: AKS clusters that use Azure CNI network plugin.
apiVersion: github.com/microsoft/PSRule/v1
kind: Selector
metadata:
  name: Azure.AKS.AzureCNI
spec:
  if:
    allOf:
    - type: '.' 
      equals: 'Microsoft.ContainerService/managedClusters' 
    - field: 'Properties.networkProfile.networkPlugin'
      equals: 'azure'

#endregion Selectors
