# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#
# Rules for Virtual Network Gateways
#

#region Rules


---
# Synopsis: Migrate from legacy SKUs to improve reliability and performance of VPN gateways.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.VNG.VPNLegacySKU
  ref: AZR-000269
  tags:
    release: GA
    ruleSet: 2020_06
    Azure.WAF/pillar: Reliability
spec:
  type:
  - Microsoft.Network/virtualNetworkGateways
  with:
  - Azure.VNG.VPNGateway
  condition:
    field: properties.sku.name
    notIn:
      - Basic
      - Standard
      - HighPerformance


---
# Synopsis: Use VPN gateways configured to operate in an Active-Active configuration to reduce connectivity downtime.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.VNG.VPNActiveActive
  ref: AZR-000270
  tags:
    release: GA
    ruleSet: 2020_06
    Azure.WAF/pillar: Reliability
spec:
  type:
  - Microsoft.Network/virtualNetworkGateways
  with:
  - Azure.VNG.VPNGateway
  condition:
    field: properties.activeActive
    equals: true

---
# Synopsis: Virtual Network Gateway (VNG) names should meet naming requirements.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.VNG.Name
  ref: AZR-000274
  tags:
    release: GA
    ruleSet: 2020_06
    Azure.WAF/pillar: Operational Excellence
spec:
  type:
  - Microsoft.Network/virtualNetworkGateways
  condition:
    allOf:
    - name: '.'
      greaterOrEquals: 1
    - name: '.'
      lessOrEquals: 80
    - name: '.'
      match: '^[a-z0-9]([a-z0-9_.-]{0,78}[a-z0-9_])?$'

---
# Synopsis: Virtual Network Gateway (VNG) connection names should meet naming requirements.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.VNG.ConnectionName
  ref: AZR-000275
  tags:
    release: GA
    ruleSet: 2020_06
    Azure.WAF/pillar: Operational Excellence
spec:
  type:
  - Microsoft.Network/connections
  condition:
    allOf:
    - name: '.'
      greaterOrEquals: 1
    - name: '.'
      lessOrEquals: 80
    - name: '.'
      match: '^[a-z0-9]([a-z0-9_.-]{0,78}[a-z0-9_])?$'

#endregion Rules

#region Selectors

---
# Synopsis: VPN Virtual Network Gateways
apiVersion: github.com/microsoft/PSRule/v1
kind: Selector
metadata:
  name: Azure.VNG.VPNGateway
spec:
  if:
    field: Properties.gatewayType
    equals: Vpn

---
# Synopsis: ExpressRoute Virtual Network Gateways
apiVersion: github.com/microsoft/PSRule/v1
kind: Selector
metadata:
  name: Azure.VNG.ERGateway
spec:
  if:
    field: Properties.gatewayType
    equals: ExpressRoute

#endregion Selectors
