# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#
# Rules for Virtual Networks (VNET)
#

#region Rules

---
# Synopsis: Virtual Network (VNET) names should meet naming requirements.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.VNET.Name
  ref: AZR-000268
  tags:
    release: 'GA'
    ruleSet: '2020_06'
    Azure.WAF/pillar: 'Operational Excellence'
spec:
  type:
  - Microsoft.Network/virtualNetworks
  condition:
    allOf:
    - name: '.'
      greaterOrEquals: 2
    - name: '.'
      lessOrEquals: 64
    - name: '.'
      match: '^[a-z0-9][a-z0-9_.-]{0,62}[a-z0-9_]$'

#endregion Rules
