# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#
# Validation rules for Automation Account
#

#region Rules

---
# Synopsis: Ensure managed identity is used for authentication.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.Automation.ManagedIdentity
  ref: AZR-000090
  tags:
    release: GA
    ruleSet: 2021_12
    Azure.WAF/pillar: 'Security'
  labels:
    Azure.ASB.v3/control: 'IM-2'
spec:
  type:
  - Microsoft.Automation/automationAccounts
  condition:
    field: identity.type
    in:
    - SystemAssigned
    - UserAssigned
    - SystemAssigned, UserAssigned

#endregion Rules
