# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#
# Rules for App Service
#

#region Rules

---
# Synopsis: Use at least a Standard App Service Plan.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AppService.MinPlan
  ref: AZR-000072
  tags:
    release: GA
    ruleSet: 2020_06
    Azure.WAF/pillar: Performance Efficiency
spec:
  type:
  - Microsoft.Web/serverfarms
  with:
    - Azure.AppService.NotElastic
  condition:
    allOf:
      - field: sku.tier
        notIn:
          - Free
          - Basic
          - Shared
      - field: sku.name
        notIn:
          - F1
          - D1
          - B1
          - B2
          - B3

---
# Synopsis: Use a Managed Identities with Azure Service apps.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AppService.ManagedIdentity
  ref: AZR-000082
  tags:
    release: GA
    ruleSet: 2020_12
    Azure.WAF/pillar: Security
  labels:
    Azure.MCSB.v1/control: [ 'IM-1', 'IM-2' ]
spec:
  type:
  - Microsoft.Web/sites
  - Microsoft.Web/sites/slots
  condition:
    field: identity.type
    in:
    - SystemAssigned
    - UserAssigned
    - SystemAssigned,UserAssigned
    - SystemAssigned, UserAssigned

---
# Synopsis: Disable client affinity for stateless services.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AppService.ARRAffinity
  ref: AZR-000083
  tags:
    release: GA
    ruleSet: 2020_06
    Azure.WAF/pillar: Performance Efficiency
spec:
  type:
  - Microsoft.Web/sites
  - Microsoft.Web/sites/slots
  condition:
    field: properties.clientAffinityEnabled
    equals: false

---
# Synopsis: Azure App Service apps should only accept encrypted connections.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AppService.UseHTTPS
  ref: AZR-000084
  tags:
    release: GA
    ruleSet: 2020_06
    Azure.WAF/pillar: Security
  labels:
    Azure.MCSB.v1/control: 'DP-3'
spec:
  type:
  - Microsoft.Web/sites
  - Microsoft.Web/sites/slots
  condition:
    field: properties.httpsOnly
    equals: true

#endregion Rules

#
# Selectors for App Service
#

#region Selectors

---
# Synopsis: App Service sites that are Web apps.
apiVersion: github.com/microsoft/PSRule/v1
kind: Selector
metadata:
  name: Azure.AppService.IsWebApp
  annotations:
    export: true
spec:
  if:
    allOf:
    - type: '.'
      in:
      - Microsoft.Web/sites
      - Microsoft.Web/sites/slots
    - anyOf:
      - field: kind
        exists: false
      - field: kind
        in:
        - app
        - app,linux

---
# Synopsis: App Service sites that are API apps.
apiVersion: github.com/microsoft/PSRule/v1
kind: Selector
metadata:
  name: Azure.AppService.IsAPIApp
  annotations:
    export: true
spec:
  if:
    allOf:
    - type: '.'
      in:
      - Microsoft.Web/sites
      - Microsoft.Web/sites/slots
    - field: kind
      equals: api

---
# Synopsis: App Service sites that are Function apps.
apiVersion: github.com/microsoft/PSRule/v1
kind: Selector
metadata:
  name: Azure.AppService.IsFunctionApp
  annotations:
    export: true
spec:
  if:
    allOf:
    - type: '.'
      in:
      - Microsoft.Web/sites
      - Microsoft.Web/sites/slots
    - field: kind
      contains: functionapp
    - field: kind
      notContains: workflowapp

---
# Synopsis: App Service sites that are Logic App Standard apps.
apiVersion: github.com/microsoft/PSRule/v1
kind: Selector
metadata:
  name: Azure.AppService.IsLogicApp
  annotations:
    export: true
spec:
  if:
    allOf:
    - type: '.'
      in:
      - Microsoft.Web/sites
      - Microsoft.Web/sites/slots
    - field: kind
      contains: workflowapp

---
# Synopsis: App Services plans that are not elastic.
apiVersion: github.com/microsoft/PSRule/v1
kind: Selector
metadata:
  name: Azure.AppService.NotElastic
  annotations:
    export: false
spec:
  if:
    allOf:
      - field: sku.name
        notStartsWith:
          - Y1
          - EP
      - anyOf:
        - field: sku.tier
          exists: false
        - field: sku.tier
          notStartsWith:
            - Dynamic
            - ElasticPremium
      - field: kind
        notEquals: elastic

#endregion Selectors
