# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#
# Validation rules for Service Bus
#

#region Rules

---
# Synopsis: Authenticate Service Bus publishers and consumers with Azure AD identities.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.ServiceBus.DisableLocalAuth
  ref: AZR-000178
  tags:
    release: GA
    ruleSet: 2022_03
    Azure.WAF/pillar: Security
  labels:
    Azure.MCSB.v1/control: 'IM-1'
spec:
  type:
    - Microsoft.ServiceBus/namespaces
  condition:
    field: properties.disableLocalAuth
    equals: true

#endregion Rules

#region Selectors

---
# Synopsis: Service Bus namespaces with a premium SKU.
apiVersion: github.com/microsoft/PSRule/v1
kind: Selector
metadata:
  name: Azure.ServiceBus.IsPremium
  annotations:
    export: true
spec:
  if:
    allOf:
      - type: '.'
        in:
          - Microsoft.ServiceBus/namespaces
      - field: sku.name
        equals: Premium

#endregion Selectors
