# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#
# Validation rules for Cognitive Services
#

#region Rules

---
# Synopsis: Restrict access of Azure AI services to authorized virtual networks.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AI.PublicAccess
  ref: AZR-000280
  alias:
    - Azure.Cognitive.PublicAccess
  tags:
    release: GA
    ruleSet: 2022_09
    Azure.WAF/pillar: Security
  labels:
    Azure.MCSB.v1/control: NS-2
spec:
  type:
  - Microsoft.CognitiveServices/accounts
  condition:
    anyOf:
    - field: properties.publicNetworkAccess
      equals: Disabled
    - field: Properties.networkAcls.defaultAction
      equals: Deny

---
# Synopsis: Configure managed identities to access Azure resources.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AI.ManagedIdentity
  ref: AZR-000281
  alias:
    - Azure.Cognitive.ManagedIdentity
  tags:
    release: GA
    ruleSet: 2022_09
    Azure.WAF/pillar: Security
  labels:
    Azure.MCSB.v1/control: [ 'IM-1', 'IM-3' ]
    Azure.Policy/id: /providers/Microsoft.Authorization/policyDefinitions/fe3fd216-4f83-4fc1-8984-2bbec80a3418
spec:
  type:
  - Microsoft.CognitiveServices/accounts
  where:
    field: kind
    in:
    - TextAnalytics
  condition:
    field: Identity.Type
    in:
    - SystemAssigned
    - UserAssigned
    - SystemAssigned,UserAssigned
    - SystemAssigned, UserAssigned

---
# Synopsis: Authenticate requests to Azure AI services with Entra ID identities.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AI.DisableLocalAuth
  ref: AZR-000282
  alias:
    - Azure.Cognitive.DisableLocalAuth
  tags:
    release: GA
    ruleSet: 2022_09
    Azure.WAF/pillar: Security
  labels:
    Azure.MCSB.v1/control: IM-1
    Azure.Policy/id:
    - /providers/Microsoft.Authorization/policyDefinitions/71ef260a-8f18-47b7-abcb-62d0673d94dc
    - /providers/Microsoft.Authorization/policyDefinitions/14de9e63-1b31-492e-a5a3-c3f7fd57f555
spec:
  type:
  - Microsoft.CognitiveServices/accounts
  condition:
    field: properties.disableLocalAuth
    equals: true

---
# Synopsis: Use Private Endpoints to access Azure AI services accounts.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AI.PrivateEndpoints
  ref: AZR-000283
  alias:
    - Azure.Cognitive.PrivateEndpoints
  tags:
    release: GA
    ruleSet: 2022_09
    Azure.WAF/pillar: Security
  labels:
    Azure.MCSB.v1/control: NS-2
spec:
  type:
  - Microsoft.CognitiveServices/accounts
  condition:
    anyOf:
    - field: properties.publicNetworkAccess
      equals: Disabled

#endregion Rules

#region Selectors

---
# Synopsis: An Azure AI services account.
apiVersion: github.com/microsoft/PSRule/v1
kind: Selector
metadata:
  name: Azure.AI.AIServices
spec:
  if:
    allOf:
      - type: .
        equals: Microsoft.CognitiveServices/accounts
      - field: kind
        equals: AIServices

#endregion Selectors
