# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#
# Rules for Virtual WANs
#

#region Rules

---
# Synopsis: Virtual WAN (vWAN) names should meet naming requirements.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.vWAN.Name
  ref: AZR-000276
  tags:
    release: 'GA'
    ruleSet: '2021_12'
    Azure.WAF/pillar: Operational Excellence
spec:
  type:
  - Microsoft.Network/virtualWans
  condition:
    allOf:
    - name: '.'
      greaterOrEquals: 1
    - name: '.'
      lessOrEquals: 80
    - name: '.'
      match: '^[a-z0-9]([a-z0-9_.-]{0,78}[a-z0-9_])?$'

#endregion Rules
