# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#
# Validation rules for Service Fabric
#

#region Rules

---
# Synopsis: Use Azure Active Directory (AAD) client authentication for Service Fabric clusters.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.ServiceFabric.AAD
  ref: AZR-000179
  tags:
    release: GA
    ruleSet: 2021_03
    Azure.WAF/pillar: Security
  labels:
    Azure.MCSB.v1/control: [ 'IM-1', 'IM-3' ]
    Azure.WAF/maturity: L1
spec:
  type:
    - Microsoft.ServiceFabric/clusters
  condition:
    field: properties.azureActiveDirectory.tenantId
    hasValue: true

---
# Synopsis: Node to node communication that is not signed and encrypted may be susceptible to man-in-the-middle attacks.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.ServiceFabric.ProtectionLevel
  ref: AZR-000488
  tags:
    release: GA
    ruleSet: 2025_06
    Azure.WAF/pillar: Security
  labels:
    Azure.WAF/maturity: L1
spec:
  type:
    - Microsoft.ServiceFabric/clusters
  condition:
    field: properties.fabricSettings[? @.name == 'Security'].parameters
    where:
      field: name
      equals: ClusterProtectionLevel
    allOf:
      - field: value
        equals: EncryptAndSign
    count: 1

#endregion Rules

#region Naming rules

---
# Synopsis: Service Fabric clusters without a standard naming convention may be difficult to identify and manage.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.ServiceFabric.Naming
  ref: AZR-000506
  tags:
    release: GA
    ruleSet: 2025_12
    Azure.WAF/pillar: Operational Excellence
  labels:
    Azure.CAF: naming
spec:
  type:
    - Microsoft.ServiceFabric/clusters
  with:
    - AZURE_SERVICE_FABRIC_CLUSTER_NAME_FORMAT
  condition:
    name: '.'
    match: true

---
# Synopsis: Service Fabric managed clusters without a standard naming convention may be difficult to identify and manage.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.ServiceFabric.ManagedNaming
  ref: AZR-000507
  tags:
    release: GA
    ruleSet: 2025_12
    Azure.WAF/pillar: Operational Excellence
  labels:
    Azure.CAF: naming
spec:
  type:
    - Microsoft.ServiceFabric/managedClusters
  with:
    - AZURE_SERVICE_FABRIC_MANAGED_CLUSTER_NAME_FORMAT
  condition:
    name: '.'
    match: true

#endregion Naming rules
