# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#
# Validation rules for Front Door
#

#region Rules

---
# Synopsis: Enable Azure Front Door Classic instance.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.FrontDoor.State
  ref: AZR-000112
  tags:
    release: 'GA'
    ruleSet: '2020_06'
    Azure.WAF/pillar: Cost Optimization
spec:
  type:
    - Microsoft.Network/frontDoors
  condition:
    field: properties.enabledState
    equals: Enabled

---
# Synopsis: Use Front Door naming requirements
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.FrontDoor.Name
  ref: AZR-000113
  tags:
    release: 'GA'
    ruleSet: '2020_06'
    Azure.WAF/pillar: Operational Excellence
spec:
  type:
    - Microsoft.Network/frontDoors
  condition:
    allOf:
      - name: '.'
        greaterOrEquals: 5
      - name: '.'
        lessOrEquals: 64
      # Alphanumerics and hyphens
      # Start and end with alphanumeric
      - name: '.'
        match: '^[A-Za-z](-|[A-Za-z0-9])*[A-Za-z0-9]$'

---
# Synopsis: Use Front Door WAF policy in prevention mode
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.FrontDoor.WAF.Mode
  ref: AZR-000114
  tags:
    release: 'GA'
    ruleSet: '2020_06'
    Azure.WAF/pillar: Security
spec:
  type:
    - Microsoft.Network/frontdoorwebapplicationfirewallpolicies
  condition:
    field: properties.policySettings.mode
    equals: Prevention

---
# Synopsis: Front Door Web Application Firewall (WAF) policy must be enabled to protect back end resources.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.FrontDoor.WAF.Enabled
  ref: AZR-000115
  tags:
    release: 'GA'
    ruleSet: '2020_06'
    Azure.WAF/pillar: Security
  labels:
    Azure.MCSB.v1/control: 'NS-6'
spec:
  type:
    - Microsoft.Network/frontdoorwebapplicationfirewallpolicies
  condition:
    field: properties.policySettings.enabledState
    equals: Enabled

---
# Synopsis: Use Front Door WAF naming requirements
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.FrontDoor.WAF.Name
  ref: AZR-000116
  tags:
    release: 'GA'
    ruleSet: '2020_12'
    Azure.WAF/pillar: Operational Excellence
spec:
  type:
    - Microsoft.Network/frontdoorwebapplicationfirewallpolicies
  condition:
    allOf:
      - name: '.'
        greaterOrEquals: 1
      - name: '.'
        lessOrEquals: 128
      # Letters or numbers
      # Start letter
      - name: '.'
        match: '^[A-Za-z][A-Za-z0-9]{0,127}$'

---
# Synopsis: Ensure Front Door uses a managed identity to authorize access to Azure resources.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.FrontDoor.ManagedIdentity
  ref: AZR-000396
  tags:
    release: GA
    ruleSet: 2023_09
    Azure.WAF/pillar: Security
  labels:
    Azure.MCSB.v1/control: IM-2
spec:
  type:
    - Microsoft.Cdn/profiles
  with:
    - Azure.FrontDoor.IsStandardOrPremium
  condition:
    field: identity.type
    in:
      - SystemAssigned
      - UserAssigned
      - SystemAssigned,UserAssigned
      - SystemAssigned, UserAssigned

#endregion Rules

#region Selectors

---
# Synopsis: Azure Front Door instances using the Standard or Premium SKU.
apiVersion: github.com/microsoft/PSRule/v1
kind: Selector
metadata:
  name: Azure.FrontDoor.IsStandardOrPremium
spec:
  if:
    allOf:
      - type: '.'
        equals: Microsoft.Cdn/profiles
      - field: sku.name
        in:
          - Standard_AzureFrontDoor
          - Premium_AzureFrontDoor

#endregion Selectors
