# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#
# Rules for Application Insights
#

#region Rules

---
# Synopsis: Configure Application Insights resources to store data in a workspace.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AppInsights.Workspace
  ref: AZR-000069
  tags:
    release: GA
    ruleSet: 2021_06
    Azure.WAF/pillar: Operational Excellence
spec:
  type:
  - microsoft.insights/components
  condition:
    field: 'properties.workspaceResourceId'
    hasValue: true

---
# Synopsis: Azure Application Insights resources names should meet naming requirements.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AppInsights.Name
  ref: AZR-000070
  tags:
    release: GA
    ruleSet: 2021_06
    Azure.WAF/pillar: Operational Excellence
  labels:
    Azure.CAF: naming
spec:
  type:
  - microsoft.insights/components
  condition:
    allOf:
    - name: '.'
      greaterOrEquals: 1
    - name: '.'
      lessOrEquals: 255
    # The name must contain between 1 to 255 characters inclusive.
    # The name only allows alphanumeric characters, periods, underscores, hyphens and parenthesis and cannot end in a period.
    - name: '.'
      match: '^[a-z0-9.\-_()]{0,254}[a-z0-9\-_()]$'

#endregion Rules
