# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#
# Validation rules for Azure Data Factory
#

#region Rules

---
# Synopsis: Consider migrating to DataFactory v2.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.DataFactory.Version
  ref: AZR-000097
  tags:
    release: GA
    ruleSet: 2020_06
    Azure.WAF/pillar: Reliability
spec:
  type:
  - Microsoft.DataFactory/datafactories
  - Microsoft.DataFactory/factories
  condition:
    type: '.'
    equals: Microsoft.DataFactory/factories

#endregion Rules
