# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#
# Validation rules for Key Vault
#

#region Rules

---
# Synopsis: Enable Soft Delete on Key Vaults to protect vaults and vault items from accidental deletion.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.KeyVault.SoftDelete
  ref: AZR-000124
  tags:
    release: GA
    ruleSet: 2020_06
    Azure.WAF/pillar: Reliability
spec:
  type:
  - Microsoft.KeyVault/vaults
  condition:
    field: Properties.enableSoftDelete
    equals: true

---
# Synopsis: Enable Purge Protection on Key Vaults to prevent early purge of vaults and vault items.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.KeyVault.PurgeProtect
  ref: AZR-000125
  tags:
    release: GA
    ruleSet: 2020_06
    Azure.WAF/pillar: Reliability
spec:
  type:
  - Microsoft.KeyVault/vaults
  condition:
    field: Properties.enablePurgeProtection
    equals: true

---
# Synopsis: Key Vaults should use Azure RBAC as the authorization system for the data plane.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.KeyVault.RBAC
  ref: AZR-000388
  tags:
    release: GA
    ruleSet: 2023_06
    Azure.WAF/pillar: Security
  labels:
    Azure.MCSB.v1/control: IM-1
spec:
  type:
  - Microsoft.KeyVault/vaults
  level: Warning
  condition:
    field: properties.enableRbacAuthorization
    equals: true

---
# Synopsis: Vaults should only accept explicitly allowed traffic.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.KeyVault.Firewall
  ref: AZR-000355
  tags:
    release: GA
    ruleSet: 2023_03
    Azure.WAF/pillar: Security
  labels:
    Azure.MCSB.v1/control: NS-2
spec:
  type:
  - Microsoft.KeyVault/vaults
  condition:
    field: properties.networkAcls.defaultAction
    equals: Deny

#endregion Rules
