# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#
# Rules for Container Apps
#

#region Rules

---
# Synopsis: Ensure insecure inbound traffic is not permitted to the container app.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.ContainerApp.Insecure
  ref: AZR-000094
  tags:
    release: GA
    ruleSet: 2023_06
    Azure.WAF/pillar: Security
  labels:
    Azure.MCSB.v1/control: NS-2
spec:
  with:
    - Azure.ContainerApp.WithIngress
  condition:
    field: properties.configuration.ingress.allowInsecure
    hasDefault: false

---
# Synopsis: Ensure managed identity is used for authentication.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.ContainerApp.ManagedIdentity
  ref: AZR-000361
  tags:
    release: GA
    ruleSet: 2023_03
    Azure.WAF/pillar: Security
  labels:
    Azure.MCSB.v1/control: IM-3
spec:
  type:
    - Microsoft.App/containerApps
  condition:
    field: identity.type
    in:
      - SystemAssigned
      - UserAssigned
      - SystemAssigned,UserAssigned
      - SystemAssigned, UserAssigned

---
# Synopsis: Container Apps should meet naming requirements.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.ContainerApp.Name
  ref: AZR-000360
  tags:
    release: GA
    ruleSet: 2023_03
    Azure.WAF/pillar: Operational Excellence
spec:
  type:
    - Microsoft.App/containerApps
  condition:
    allOf:
      - name: '.'
        greaterOrEquals: 2
      - name: '.'
        lessOrEquals: 32
      - name: '.'
        isLower: true
      - name: '.'
        match: '^([a-z][0-9a-z-]{0,30}[0-9a-z])$'

---
# Synopsis: Ensure public network access for Container Apps environment is disabled.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.ContainerApp.PublicAccess
  ref: AZR-000363
  tags:
    release: GA
    ruleSet: 2023_03
    Azure.WAF/pillar: Security
  labels:
    Azure.MCSB.v1/control: NS-2
spec:
  type:
    - Microsoft.App/managedEnvironments
  condition:
    allOf:
      - field: properties.vnetConfiguration.internal
        equals: true
      - field: properties.vnetConfiguration.infrastructureSubnetId
        hasValue: true

---
# Synopsis: Limit inbound communication for Container Apps is limited to callers within the Container Apps Environment.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.ContainerApp.ExternalIngress
  ref: AZR-000362
  tags:
    release: GA
    ruleSet: 2023_03
    Azure.WAF/pillar: Security
spec:
  with:
    - Azure.ContainerApp.WithIngress
  where:
    value:
      $:
        configuration: AZURE_CONTAINERAPPS_RESTRICT_INGRESS
    equals: true
  condition:
    field: properties.configuration.ingress.external
    hasDefault: false

---
# Synopsis: Use of Azure Files volume mounts to persistent storage container data.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.ContainerApp.Storage
  ref: AZR-000364
  tags:
    release: GA
    ruleSet: 2023_03
    Azure.WAF/pillar: Reliability
spec:
  type:
    - Microsoft.App/containerApps
  where:
    field: properties.template.volumes
    greater: 0
  condition:
    field: properties.template.volumes
    allOf:
      - field: storageType
        equals: AzureFile

---
# Synopsis: Disable session affinity to prevent unbalanced distribution.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.ContainerApp.DisableAffinity
  ref: AZR-000378
  tags:
    release: GA
    ruleSet: 2023_09
    Azure.WAF/pillar: Performance Efficiency
spec:
  with:
    - Azure.ContainerApp.WithIngress
  condition:
    field: properties.configuration.ingress.stickySessions.affinity
    hasDefault: none

---
# Synopsis: Migrate from retired API version to a supported version.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.ContainerApp.APIVersion
  ref: AZR-000400
  tags:
    release: GA
    ruleSet: 2023_09
    Azure.WAF/pillar: Operational Excellence
spec:
  type:
    - Microsoft.App/containerApps
  condition:
    field: apiVersion
    notIn:
      - 2022-06-01-preview
      - 2022-11-01-preview

---
# Synopsis: Use multiple replicas to remove a single point of failure.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.ContainerApp.MinReplicas
  ref: AZR-000413
  tags:
    release: GA
    ruleSet: 2024_06
    Azure.WAF/pillar: Reliability
spec:
  type:
  - Microsoft.App/containerApps
  condition:
    field: properties.template.scale.minReplicas
    greaterOrEquals: 2

#endregion Rules

#region Selectors

---
# Synopsis: Get container apps with an ingress configuration.
apiVersion: github.com/microsoft/PSRule/v1
kind: Selector
metadata:
  name: Azure.ContainerApp.WithIngress
spec:
  if:
    allOf:
      - type: '.'
        equals: Microsoft.App/containerApps
      - field: 'properties.configuration.ingress'
        exists: true

#endregion Selectors
