# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#
# Rules for Network Security Groups (NSGs)
#

#region Rules

---
# Synopsis: Network Security Group (NSG) names should meet naming requirements.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.NSG.Name
  tags:
    release: 'GA'
    ruleSet: '2020_06'
spec:
  type:
  - Microsoft.Network/networkSecurityGroups
  condition:
    allOf:
    - name: '.'
      greaterOrEquals: 1
    - name: '.'
      lessOrEquals: 80
    - name: '.'
      match: '^[a-z0-9]([a-z0-9_.-]{0,78}[a-z0-9_])?$'

#endregion Rules
