# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#
# Rules for Redis Cache Enterprise
#

#region Rules

---
# Synopsis: Redis Cache Enterprise should reject TLS versions older than 1.2.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.RedisEnterprise.MinTLS
  ref: AZR-000301
  tags:
    release: GA
    ruleSet: 2022_09
    Azure.WAF/pillar: Security
  labels:
    Azure.MCSB.v1/control: DP-3
spec:
  type:
  - Microsoft.Cache/redisEnterprise
  condition:
    field: properties.minimumTlsVersion
    hasDefault: '1.2'

#endregion Rules
