# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#
# Rules for App Service
#

#region Rules

---
# Synopsis: Use a Managed Identities with Azure Service apps.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AppService.ManagedIdentity
  tags:
    release: 'GA'
    ruleSet: 2020_12
spec:
  type:
  - Microsoft.Web/sites
  - Microsoft.Web/sites/slots
  condition:
    field: identity.type
    in:
    - SystemAssigned
    - UserAssigned
    - SystemAssigned, UserAssigned

#endregion Rules
