# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#
# Validation rules for Azure Databricks
#

---
# Synopsis: Use Databricks workspaces configured for secure cluster connectivity.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.Databricks.SecureConnectivity
  ref: AZR-000393
  tags:
    release: GA
    ruleSet: 2023_09
    Azure.WAF/pillar: Security
spec:
  type:
  - Microsoft.Databricks/workspaces
  condition:
    allOf:
      - field: properties.parameters.enableNoPublicIp.value
        isBoolean: true
      - field: properties.parameters.enableNoPublicIp.value
        equals: true

---
# Synopsis: Use non-Trial SKUs for Databricks workspaces.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.Databricks.SKU
  ref: AZR-000409
  tags:
    release: GA
    ruleSet: 2024_01
    Azure.WAF/pillar: Performance Efficiency
spec:
  type:
  - Microsoft.Databricks/workspaces
  condition:  
     field: sku.name  
     notEquals: trial  

---
# Synopsis: Azure Databricks Workspaces should disable public network access.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.Databricks.PublicAccess
  ref: AZR-000410
  tags:
    release: GA
    ruleSet: 2024_01
    Azure.WAF/pillar: Security
spec:
  type:
  - Microsoft.Databricks/workspaces
  condition:  
    field: properties.publicNetworkAccess  
    equals: Disabled  
