# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#
# Validation rules for Azure Recovery Services Vault (RSV)
#

#region Rules

---
# Synopsis: Recovery Services vaults should meet naming requirements.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.RSV.Name
  ref: AZR-000350
  tags:
    release: 'GA'
    ruleSet: '2022_12'
    Azure.WAF/pillar: 'Operational Excellence'
spec:
  type:
  - Microsoft.RecoveryServices/vaults
  condition:
    allOf:
    - name: '.'
      greaterOrEquals: 2
    - name: '.'
      lessOrEquals: 50
    - name: '.'
      match: '^[A-Za-z][A-Za-z0-9-]{1,49}$'

---
# Synopsis: Ensure immutability is configured to protect backup data.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.RSV.Immutable
  ref: AZR-000397
  tags:
    release: GA
    ruleSet: 2023_09
    Azure.WAF/pillar: 'Security'
  labels:
    Azure.MCSB.v1/control: 'DP-2'
spec:
  type:
    - Microsoft.RecoveryServices/vaults
  condition:
    field: properties.securitySettings.immutabilitySettings.state
    in:
      - Unlocked
      - Locked

#endregion Rules
