# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#
# Rules for Private Endpoints
#

#region Rules

---
# Synopsis: Private Endpoint names should meet naming requirements.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.PrivateEndpoint.Name
  ref: AZR-000153
  tags:
    release: GA
    ruleSet: 2021_12
    Azure.WAF/pillar: Operational Excellence
  labels:
    Azure.CAF: naming
spec:
  type:
  - Microsoft.Network/privateEndpoints
  condition:
    allOf:
    - name: '.'
      greaterOrEquals: 2
    - name: '.'
      lessOrEquals: 64
    - name: '.'
      match: '^[a-z0-9][a-z0-9_.-]{0,62}[a-z0-9_]$'

#endregion Rules
