# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#
# Validation rules for Service Bus
#

#region Rules

---
# Synopsis: Authenticate Service Bus publishers and consumers with Azure AD identities.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.ServiceBus.DisableLocalAuth
  ref: AZR-000178
  tags:
    release: GA
    ruleSet: 2022_03
    Azure.WAF/pillar: Security
  labels:
    Azure.MCSB.v1/control: IM-1
    Azure.WAF/maturity: 'L1'
spec:
  type:
    - Microsoft.ServiceBus/namespaces
  condition:
    field: properties.disableLocalAuth
    equals: true

---
# Synopsis: Enforce namespaces to require that clients send and receive data with TLS 1.2 version.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.ServiceBus.MinTLS
  ref: AZR-000315
  tags:
    release: GA
    ruleSet: 2022_12
    Azure.WAF/pillar: Security
  labels:
    Azure.MCSB.v1/control: DP-3
    Azure.WAF/maturity: 'L1'
spec:
  type:
    - Microsoft.ServiceBus/namespaces
  condition:
    field: properties.minimumTlsVersion
    equals: '1.2'

---
# Synopsis: Enhance resilience to regional outages by replicating namespaces.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.ServiceBus.GeoReplica
  ref: AZR-000444
  tags:
    release: preview
    ruleSet: 2024_09
    Azure.WAF/pillar: Reliability
spec:
  type:
    - Microsoft.ServiceBus/namespaces
  condition:
    allOf:
      # Geo-replication is only available for the Premium SKU.
      - field: sku.name
        equals: Premium
      - field: properties.geoDataReplication.locations
        greaterOrEquals: 2

#endregion Rules

#region Selectors

---
# Synopsis: Service Bus namespaces with a premium SKU.
apiVersion: github.com/microsoft/PSRule/v1
kind: Selector
metadata:
  name: Azure.ServiceBus.IsPremium
  annotations:
    export: true
spec:
  if:
    allOf:
      - type: '.'
        in:
          - Microsoft.ServiceBus/namespaces
      - field: sku.name
        equals: Premium
#endregion Selectors
