# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#
# Validation rules for Automation Account
#

#region Rules

---
# Synopsis: Ensure managed identity is used for authentication.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.Automation.ManagedIdentity
  ref: AZR-000090
  tags:
    release: GA
    ruleSet: 2021_12
spec:
  type:
  - Microsoft.Automation/automationAccounts
  condition:
    field: Identity.Type
    in:
    - SystemAssigned
    - UserAssigned
    - SystemAssigned, UserAssigned

#endregion Rules
