# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#
# Rules for Azure Defender
#

#region Rules

---
# Synopsis: Consider enabling Defender for Containers
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.Defender.Containers
  ref: AZR-000289
  tags:
    release: 'GA'
    ruleSet: '2022_09'
spec:
  level: Error
  where:
    name: '.'
    equals: Containers
  type:
  - Microsoft.Security/pricings
  condition:
    field: 'properties.pricingTier'
    equals: 'Standard'

---
# Synopsis: Consider enabling Defender for Servers
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.Defender.Servers
  ref: AZR-000290
  tags:
    release: 'GA'
    ruleSet: '2022_09'
spec:
  level: Error
  where:
    name: '.'
    equals: VirtualMachines
  type:
  - Microsoft.Security/pricings
  condition:
    allOf:
      - field: 'properties.pricingTier'
        equals: 'Standard'
      - field: 'properties.subPlan'
        equals: 'P2'

---
# Synopsis: Consider enabling Defender for SQL
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.Defender.SQL
  ref: AZR-000291
  tags:
    release: 'GA'
    ruleSet: '2022_09'
spec:
  level: Error
  where:
    name: '.'
    equals: SqlServers
  type:
  - Microsoft.Security/pricings
  condition:
    field: 'properties.pricingTier'
    equals: 'Standard'

---
# Synopsis: Consider enabling Defender for App Service
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.Defender.AppServices
  ref: AZR-000292
  tags:
    release: 'GA'
    ruleSet: '2022_09'
spec:
  level: Error
  where:
    name: '.'
    equals: AppServices
  type:
  - Microsoft.Security/pricings
  condition:
    field: 'properties.pricingTier'
    equals: 'Standard'

---
# Synopsis: Consider enabling Defender for Storage
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.Defender.Storage
  ref: AZR-000293
  tags:
    release: 'GA'
    ruleSet: '2022_09'
spec:
  level: Error
  where:
    name: '.'
    equals: StorageAccounts
  type:
  - Microsoft.Security/pricings
  condition:
    field: 'properties.pricingTier'
    equals: 'Standard'

#endregion Rules