# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#
# Validation rules for Azure CDN
#

#region Rules

---
# Synopsis: Enforce HTTPS for client connections.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.CDN.HTTP
  ref: AZR-000093
  tags:
    release: 'GA'
    ruleSet: '2020_06'
    Azure.WAF/pillar: 'Security'
  labels:
    Azure.MCSB.v1/control: 'DP-3'
spec:
  type:
    - Microsoft.Cdn/profiles/endpoints
  condition:
    field: properties.isHttpAllowed
    equals: false

---
# Synopsis: Ensure managed identity is used for Azure Front Door to allow support for Azure AD authentication.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.CDN.ManagedIdentity
  ref: AZR-000396
  tags:
    release: GA
    ruleSet: 2023_09
    Azure.WAF/pillar: 'Security'
  labels:
    Azure.MCSB.v1/control: 'IM-2'
spec:
  type:
    - Microsoft.Cdn/profiles
  with:
    - Azure.CDN.IsStandardOrPremiumFD
  condition:
    field: identity.type
    in:
      - SystemAssigned
      - UserAssigned
      - SystemAssigned,UserAssigned

#endregion Rules

#region Selectors

---
# Synopsis: Azure Front Door instances using the Standard or Premium SKU.
apiVersion: github.com/microsoft/PSRule/v1
kind: Selector
metadata:
  name: Azure.CDN.IsStandardOrPremiumFD
spec:
  if:
    field: sku.name
    in:
      - Standard_AzureFrontDoor
      - Premium_AzureFrontDoor

#endregion Selectors
