# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#
# Selectors for Application Gateways
#

#region Rules

---
# Synopsis: Application Gateways should use a WAF.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AppGwWAF.Enabled
  ref: AZR-000309
  tags:
    release: GA
    ruleSet: 2022_09
    Azure.WAF/pillar: Security
spec:
  type:
  - Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies
  condition:
    allOf:
    # WAF policy is enabled
    - field: Properties.policySettings.state
      equals: 'Enabled'

---
# Synopsis: Application Gateways WAF should be in prevention mode.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AppGwWAF.PreventionMode
  ref: AZR-000302
  tags:
    release: GA
    ruleSet: 2022_09
    Azure.WAF/pillar: Security
spec:
  type:
  - Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies
  condition:
    allOf:
    # WAF policy is set to prevention mode
    - field: Properties.policySettings.mode
      equals: 'Prevention'

---

# Synopsis: Application Gateways WAF should have no exclusions.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AppGwWAF.Exclusions
  ref: AZR-000303
  tags:
    release: GA
    ruleSet: 2022_09
    Azure.WAF/pillar: Security
spec:
  type:
  - Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies
  condition:
    anyOf:
    # WAF policy has no exclusions
    - field: properties.managedRules.exclusions
      exists: false
    - field: properties.managedRules.exclusions
      count: 0

---

# Synopsis: Application Gateways WAF should have at least 2 Rule Groups. One for OWASP and one for Microsoft_BotManagerRuleSet.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AppGwWAF.RuleGroups
  ref: AZR-000304
  tags:
    release: GA
    ruleSet: 2024_03
    Azure.WAF/pillar: Security
spec:
  type:
  - Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies
  condition:
    allOf:
    # WAF policy has at least two rule groups. OWASP 3.2 is the minimum. Microsoft_BotManagerRuleSet 1.0 is the minimum.
    - field: Properties.managedRules.managedRuleSets
      greaterOrEquals: 2
    - field: Properties.managedRules.managedRuleSets[0].ruleSetType
      equals: OWASP 
    - field: Properties.managedRules.managedRuleSets[0].ruleSetVersion
      version: '>=3.2'
    - field: Properties.managedRules.managedRuleSets[1].ruleSetType
      equals: Microsoft_BotManagerRuleSet
    - field: Properties.managedRules.managedRuleSets[1].ruleSetVersion
      version: '>=1.0'

#endregion Rules
