# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#
# Rules for Redis Cache
#

#region Rules

---
# Synopsis: Use Azure Cache for Redis instances of at least Standard C1.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.Redis.MinSKU
  ref: AZR-000159
  tags:
    release: GA
    ruleSet: 2020_12
    Azure.WAF/pillar: Performance Efficiency
spec:
  type:
    - Microsoft.Cache/Redis
  with:
    - Azure.Redis.HasSku
  condition:
    anyOf:
      - field: properties.sku.name
        equals: Premium
      - allOf:
          - field: properties.sku.name
            equals: Standard
          - field: properties.sku.capacity
            greaterOrEquals: 1

---
# Synopsis: Redis Cache should only accept secure connections.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.Redis.NonSslPort
  ref: AZR-000163
  tags:
    release: GA
    ruleSet: 2020_06
    Azure.WAF/pillar: Security
  labels:
    Azure.MCSB.v1/control: DP-3
    Azure.WAF/maturity: L1
spec:
  type:
    - Microsoft.Cache/Redis
  condition:
    field: properties.enableNonSslPort
    equals: false

---
# Synopsis: Redis Cache should reject TLS versions older than 1.2.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.Redis.MinTLS
  ref: AZR-000164
  tags:
    release: GA
    ruleSet: 2020_06
    Azure.WAF/pillar: Security
  labels:
    Azure.MCSB.v1/control: DP-3
    Azure.WAF/maturity: L1
spec:
  type:
    - Microsoft.Cache/Redis
  condition:
    field: properties.minimumTlsVersion
    hasDefault: '1.2'

---
# Synopsis: Redis cache should disable public network access.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.Redis.PublicNetworkAccess
  ref: AZR-000165
  tags:
    release: GA
    ruleSet: 2022_03
    Azure.WAF/pillar: Security
  labels:
    Azure.MCSB.v1/control: NS-2
spec:
  type:
    - Microsoft.Cache/Redis
  condition:
    field: properties.publicNetworkAccess
    equals: Disabled

---
# Synopsis: Use Entra ID authentication with cache instances.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.Redis.EntraID
  ref: AZR-000427
  tags:
    release: GA
    ruleSet: 2024_06
    Azure.WAF/pillar: Security
  labels:
    Azure.MCSB.v1/control: IM-1
    Azure.WAF/maturity: L1
spec:
  type:
    - Microsoft.Cache/Redis
  condition:
    field: properties.redisConfiguration.aad-enabled
    equals: 'True'

---
# Synopsis: Authenticate Redis Cache clients with Entra ID identities.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.Redis.LocalAuth
  ref: AZR-000496
  tags:
    release: GA
    ruleSet: 2025_09
    Azure.WAF/pillar: Security
  labels:
    Azure.MCSB.v1/control: IM-1
    Azure.WAF/maturity: L1
spec:
  type:
    - Microsoft.Cache/Redis
  condition:
    field: properties.disableAccessKeyAuthentication
    equals: true

#endregion Rules

#region Selectors

---
# Synopsis: Azure Cache for Redis with a SKU set.
apiVersion: github.com/microsoft/PSRule/v1
kind: Selector
metadata:
  name: Azure.Redis.HasSku
  annotations:
    export: false
spec:
  if:
    allOf:
      - type: '.'
        equals: Microsoft.Cache/Redis
      - field: properties.sku.capacity
        exists: true
      - field: properties.sku.family
        exists: true
      - field: properties.sku.name
        exists: true

---
# Synopsis: Azure Cache for Redis with Enterprise SKU.
apiVersion: github.com/microsoft/PSRule/2025-01-01
kind: Selector
metadata:
  name: Azure.Redis.IsEnterprise
spec:
  if:
    allOf:
      - type: .
        equals: Microsoft.Cache/redisEnterprise
      - field: sku.name
        startsWith:
         - 'Enterprise_'
         - 'EnterpriseFlash_'

---
# Synopsis: Azure Managed Redis.
apiVersion: github.com/microsoft/PSRule/2025-01-01
kind: Selector
metadata:
  name: Azure.Redis.IsManaged
spec:
  if:
    allOf:
      - type: .
        equals: Microsoft.Cache/redisEnterprise
      - field: sku.name
        notStartsWith:
         - 'Enterprise_'
         - 'EnterpriseFlash_'

#endregion Selectors
