# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#
# Validation rules for Azure Virtual Machine Scale Sets
#

#region Rules

---
# Synopsis: Application or infrastructure relying on a virtual machine scale sets may fail if VM instances are unhealthy.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.VMSS.AutoInstanceRepairs
  ref: AZR-000426
  tags:
    release: GA
    ruleSet: 2025_06
    Azure.WAF/pillar: Reliability
spec:
  type:
    - Microsoft.Compute/virtualMachineScaleSets
  condition:
    field: properties.automaticRepairsPolicy.enabled
    equals: true

#endregion Rules
