# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
# Synopsis: Azure resources associated with Azure Cloud Shell.
apiVersion: github.com/microsoft/PSRule/v1
kind: Selector
metadata:
  name: Azure.Usage.CloudShell
  annotations:
    export: true
spec:
  if:
    field: tags.ms-resource-usage
    equals: azure-cloud-shell

---
# Synopsis: Azure resources not associated with Azure Cloud Shell.
apiVersion: github.com/microsoft/PSRule/v1
kind: Selector
metadata:
  name: Azure.Usage.NotCloudShell
  annotations:
    export: false
spec:
  if:
    field: tags.ms-resource-usage
    notEquals: azure-cloud-shell

---
# Synopsis: Resources that supports tags.
apiVersion: github.com/microsoft/PSRule/v1
kind: Selector
metadata:
  name: Azure.Resource.SupportsTags
  annotations:
    export: true
spec:
  if:
    allOf:

    # Only include resource types
    - type: '.'
      like: 'Microsoft.*/*'

    # Exclude resource providers that do not support tags
    - type: '.'
      notStartsWith:
      - Microsoft.Addons/
      - Microsoft.Advisor/
      - Microsoft.Authorization/
      - Microsoft.Billing/
      - Microsoft.Blueprint/
      - Microsoft.Capacity/
      - Microsoft.Classic
      - Microsoft.Consumption/
      - Microsoft.Gallery/
      - Microsoft.Security/
      - microsoft.support/
      - Microsoft.WorkloadMonitor/

    # Exclude resource types that do not support tags
    - type: '.'
      notIn:
      - Microsoft.Subscription
      - Microsoft.AzureActiveDirectory/b2ctenants
    - type: '.'
      notEndsWith:
      - /providers/roleAssignments
      - /providers/diagnosticSettings

    # Specific exception cases
    - anyOf:
      - type: '.'
        notStartsWith: Microsoft.Resources/
      - type: '.'
        in:
        - Microsoft.Resources/deploymentScripts
        - Microsoft.Resources/resourceGroups
        - Microsoft.Resources/templateSpecs
        - Microsoft.Resources/templateSpecs/versions

    - anyOf:
      - type: '.'
        notStartsWith: Microsoft.CostManagement/
      - type: '.'
        in:
        - Microsoft.CostManagement/Connectors

    - anyOf:
      - type: '.'
        notStartsWith: Microsoft.Insights/
      - type: '.'
        in:
        - Microsoft.Insights/actionGroups
        - Microsoft.Insights/activityLogAlerts
        - Microsoft.Insights/alertRules
        - Microsoft.Insights/autoscaleSettings
        - Microsoft.Insights/components
        - Microsoft.Insights/dataCollectionEndpoints
        - Microsoft.Insights/dataCollectionRules
        - Microsoft.Insights/guestDiagnosticSettings
        - Microsoft.Insights/metricAlerts
        - Microsoft.Insights/notificationGroups
        - Microsoft.Insights/privateLinkScopes
        - Microsoft.Insights/scheduledQueryRules
        - Microsoft.Insights/webTests
        - Microsoft.Insights/workbooks
        - Microsoft.Insights/workbookTemplates

    - anyOf:
      - type: '.'
        notLike: 'Microsoft.*/*/*'
      - type: '.'
        in:
        - Microsoft.Automation/automationAccounts/runbooks
        - Microsoft.Automation/automationAccounts/configurations
        - Microsoft.Automation/automationAccounts/compilationJobs
        - Microsoft.Automation/automationAccounts/modules
        - Microsoft.Automation/automationAccounts/nodeConfigurations
        - Microsoft.Automation/automationAccounts/python2Packages
        - Microsoft.Automation/automationAccounts/watchers
        - Microsoft.Resources/templateSpecs/versions
