# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# Visual Studio Code image with .NET

# NOTE:
# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/main/containers/dotnet

ARG VARIANT="7.0-bullseye-slim"
FROM mcr.microsoft.com/vscode/devcontainers/dotnet:${VARIANT}
