#
# Update policy alias data
#

# NOTES:
# Automatically updates policy alias data stored in data/ with the latest versions.

name: BumpAliases

on:
  schedule:
    - cron:  '0 0 2 * *' # 00:00 on second day of each month
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        run: |
          git config user.name github-actions
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Bump Aliases
        uses: Azure/powershell@v1
        with:
          inlineScript: |
            Install-Module InvokeBuild -MinimumVersion 5.4.0 -Scope CurrentUser -Force
            Invoke-Build ExportAliases
          azPSVersion: latest

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Bump aliases data
          title: Bump aliases data
          body: 'Updates to aliases.json'
          delete-branch: true